name: Build WebAssembly
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: emscripten/emsdk:4.0.7

    steps:
      - uses: actions/checkout@v4

      - name: Install Typescript
        run: npm install -g typescript

      - name: Compile
        run: make wasm-all
